//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DediPro.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MAIN_FORM                   101
#define IDD_PROPPAGE_MEDIUM             106
#define IDD_CONFIG_MISC                 106
#define IDR_MAINFRAME                   128
#define IDR_DediProTYPE                 129
#define IDR_USERTOOLBAR                 132
#define IDD_SELECT_MEMORY_TYPE          132
#define IDC_IMAGE                       133
#define IDB_TOOLBAR_DRAW                134
#define IDB_TOOLBAR_DRAW_HOT            135
#define IDB_TOOLBAR_DRAW_DISABLED       136
#define IDD_CONFIG_HEX                  136
#define IDD_COMPARE_LOG                 137
#define IDD_CONFIG_FLASHCARD_SETTING    138
#define IDD_EEPROM_HISTORY              140
#define IDD_CONFIG_LOAD_FILE            144
#define IDD_CONFIG_BATCH                146
#define IDR_MENU_PROG                   147
#define IDR_MENU_AUTO                   148
#define IDD_CONFIG_PROG                 149
#define IDB_LEGEND                      151
#define IDD_TYPE_AMBIGUITY              152
#define IDD_CONFIG_SR                   153
#define IDB_POINT                       154
#define IDD_CONFIG_STANDALONE_BOARD     155
#define IDD_CONFIG_ENGINEERING_MODE     156
#define IDB_SPECIAL_LOGO                157
#define IDB_ADVCFG                      159
#define IDD_MEMORY_DETECTION            160
#define IDD_CONFIG_FREESCALE            161
#define IDB_NUMONYX_LOGO                161
#define IDC_GRPPARAM                    1003
#define IDC_OPTCARD                     1004
#define IDC_GRPPARAM2                   1004
#define IDC_OPTMEM1                     1005
#define IDC_GRPPARAM3                   1005
#define IDC_GRPBATCHCONFIG              1005
#define IDC_OPTMEM2                     1006
#define IDC_MANUFACTURE                 1008
#define IDC_GRID                        1008
#define IDC_GRIDFILE                    1008
#define IDC_VER                         1010
#define ID_OK                           1011
#define IDC_OPTHEX                      1012
#define IDC_OPTASCII                    1013
#define IDC_CRC                         1018
#define IDC_COMPARE                     1021
#define IDC_EDIT1                       1022
#define IDC_ROWJUMP                     1022
#define IDC_CONFIG_REGISTER             1022
#define IDC_LBLFIRMWAREVERSION          1023
#define IDC_LBLFIRMWAREVERSION2         1024
#define IDC_HEX                         1029
#define IDC_FILE                        1029
#define IDC_ASCII                       1030
#define IDC_COPYWRITE                   1030
#define IDC_MEMORY                      1030
#define IDC_URL                         1031
#define IDC_SUPPORTMAIL                 1032
#define IDC_LST_SEQUENCES               1034
#define IDC_LOGVIEW                     1034
#define IDC_LSTTYPE                     1034
#define IDC_CBOSIZELST                  1035
#define IDC_CHKBLANKCHECK               1036
#define IDC_CHKERASE                    1037
#define IDC_CHKPROG                     1041
#define IDC_CHKVERIFY                   1042
#define IDC_CHKPROTECT                  1043
#define IDC_BTNRESET                    1044
#define IDC_CNTSUCCESS                  1045
#define IDC_CNTERRERASE                 1046
#define IDC_CNTERRPROG                  1047
#define IDC_CNTERRVERIFY                1048
#define IDC_PROMPT                      1050
#define IDC_LBLFILENAME2                1055
#define IDC_LBLFILECHKSUM2              1056
#define IDC_OPTION_WHOLECHIP            1058
#define IDC_OPTION_PARTIALCHIP          1059
#define IDC_GRPINFO                     1062
#define IDC_SELEC_AUTO                  1066
#define IDC_SELEC_MANU                  1067
#define IDC_MEMTYPLIST                  1068
#define IDC_DESCAUTO                    1069
#define IDC_DESCMANU                    1070
#define IDC_DESCCAUTI                   1071
#define IDC_GRPSEL                      1073
#define IDC_FIND                        1073
#define IDC_CHECK1                      1078
#define IDC_LBLFILENAME                 1082
#define IDC_LBLFILECHKSUM               1083
#define IDC_IDENTIFIED_TYPE             1084
#define IDC_ADDR_FROM                   1086
#define IDC_LENGTH                      1088
#define IDC_OPTPRESET_CUSTOM            1090
#define IDC_OPTPRESET_DOWNLOAD_WHOLE_FILE 1091
#define IDC_OPTPRESET_DOWNLOAD_WHOLE_FILE_WITHOUT_BLANKCHECK 1092
#define IDC_OPTPRESET_DOWNLOAD_PARTIAL_FILE 1093
#define IDC_NOTE                        1098
#define IDC_BTNCANCEL                   1102
#define IDC_REFRESH                     1102
#define IDC_WRITE_NEW_VALUE             1103
#define IDC_LSTSUPPORTED_CHIPS          1108
#define IDC_LST_FILES                   1108
#define IDC_PADPROMPT                   1109
#define IDC_RAW_RESULTS                 1111
#define IDC_CHKFILL_WITH_00             1112
#define IDC_CHKRELOAD_FILE              1113
#define IDC_CHK_FILL_WITH_00_NO_BLKCHK  1115
#define IDC_CHK_FILL_WITH_00_FOR_BLKCHK 1116
#define IDC_LBLFILESIZE                 1118
#define IDC_CHIP_PARAMETER_CAPTION_TYPE 1119
#define IDC_CHIP_PARAMETER_CAPTION_MSIZE 1120
#define IDC_LBLFILESIZE2                1121
#define IDC_VALUE_CURRENT               1122
#define IDC_NEW_VALUE                   1123
#define IDC_FULL_UPDATE                 1124
#define IDC_CHIP_PARAMETER_CAPTION_MANU 1125
#define IDC_CHIP_PARAMETER_CAPTION_MANUURL 1126
#define IDC_PARTIAL_UPDATE              1127
#define IDC_CHIP_PARAMETER_CAPTION_MANUID 1128
#define IDC_CHIP_PARAMETER_CAPTION_JID  1129
#define IDC_UPDATE_OPTION_CHECK         1130
#define IDC_LBLTYPE                     1131
#define IDC_SA_EPV                      1131
#define IDC_LBLMSIZE                    1132
#define IDC_SA_BEPV                     1132
#define IDC_PARTIAL_UPDATE_CHECK        1133
#define IDC_SA_PV                       1133
#define IDC_LBLVPPACC_ENABLE            1134
#define IDC_LBLVPPACC_ENABLE2           1135
#define IDC_MEM_DENSITY                 1135
#define IDC_ENABLE_VPP_ACC              1136
#define IDC_LBLTARGET_CHIP_SIZE         1136
#define IDC_LBLMANU                     1137
#define CBO_FILEFAPTH                   1137
#define IDC_LBLMANUURL                  1138
#define IDC_SEND                        1138
#define IDC_LBLTARGET_CHIP_SIZE2        1139
#define IDC_LBLMANUID                   1140
#define IDC_BATCH_ADDR_FROM             1140
#define IDC_LBLJID                      1141
#define IDC_LBLSA_SEQUENCE              1142
#define IDC_LBLBOARDTYPE                1143
#define IDC_LBLBOARDTYPE2               1144
#define IDC_LBLSA_SEQUENCE2             1145
#define IDC_BYTECOUNT                   1146
#define IDC_LBLBOARDVCC                 1147
#define IDC_OUT                         1147
#define IDC_LBLBOARDVCC2                1148
#define IDC_NEEDRETURN                  1148
#define IDC_RETURNED_BYTES              1149
#define IDC_IN                          1149
#define IDC_LBLBOARDVPP                 1149
#define IDC_LBLBOARDVCC4                1150
#define IDC_LBLBOARDVPP2                1150
#define IDC_NEEDMONITOR                 1151
#define IDC_SR                          1152
#define IDC_ENGMODE_WARNING             1153
#define IDC_SECONDS                     1154
#define IDC_CHK_VPP                     1155
#define IDC_LIST                        1156
#define IDC_TIMING                      1158
#define IDC_CHIP_INFO                   1159
#define IDC_FILE_INFO                   1160
#define IDC_OPEN                        1161
#define IDC_READMEM                     1162
#define IDC_CHIP_PROGRESS               1165
#define IDC_PROGRESS2                   1166
#define IDC_FILE_PROGRESS               1166
#define IDC_HOTKEY1                     1167
#define IDC_FORMAT_RAWBIN               1170
#define IDC_NEXTDIFF                    1170
#define IDC_FORMAT_INTELHEX             1171
#define IDC_JUMPTO                      1171
#define IDC_FORMAT_MOTOS19              1172
#define IDC_JUMPADDR                    1172
#define IDC_FORMAT_ROM                  1173
#define IDC_FILEBUFF2FILE               1173
#define IDC_FILEBUFF2CHIP               1174
#define IDC_CHIPBUFF2FILE               1175
#define IDC_CHIPBUFF2CHIP               1176
#define IDC_WARNING_RELOAD_FILE         1177
#define IDC_WARNING_RELOAD_FILE2        1178
#define IDC_WARNING_RELOAD_CHIP         1178
#define IDC_MANU_LIST                   1178
#define IDC_LIST2                       1179
#define IDC_CHIP_LIST                   1179
#define IDC_VCC3_5                      1180
#define IDC_VCC3_6                      1181
#define IDC_VCC1_8                      1181
#define IDC_MANU                        1181
#define IDC_LIST1                       1182
#define IDC_CHIP                        1182
#define IDC_TYPELIST                    1182
#define IDC_FILTERLIST                  1183
#define IDC_LOGO                        1184
#define ID_TOOLBUTTON_BLANKCHK          32772
#define ID_TOOLBUTTON_ERASE             32773
#define ID_TOOLBUTTON_READ              32774
#define ID_TOOLBUTTON_PROG              32775
#define ID_TOOLBUTTON_VERIFY            32776
#define ID_TOOLBUTTON_AUTO              32777
#define ID_TOOLBUTTON_DLDCARD           32778
#define ID_TOOLBUTTON_HEX               32779
#define ID_TOOLBUTTON_SELTYPE           32780
#define ID_TOOLBUTTON_LOADFILE          32781
#define ID_HELP_USERMANUAL              32783
#define ID_HELP_LAUNCHCALCULATER        32784
#define ID_TOOLBUTTON_ADVCFG            32786
#define ID_HELP_UPDATEFIRMWARE          32787
#define ID_TOOLBUTTON_EEHISTO           32788
#define ID_AUTO_MOREOPTIONS             32799
#define ID_PROG_MOREOPTIONS             32800
#define ID_TOOLBUTTON_STATUS_REGISTER   32801
#define ID_TOOLBUTTON_CARDCONFIG        32802
#define ID_TOOLBUTTON_ENGINEERING_MODE  32803
#define ID_BUTTON32824                  32824
#define ID_TOOLBUTTON_FREESCALE         32824
#define ID_HELP_FIRMWAREAUTOUPDATE      32825

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32826
#define _APS_NEXT_CONTROL_VALUE         1185
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
